name: 'kraftr'

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/

  preChecks:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check for missing change logs
        run: common/scripts/install-run-rush.js change -v

  install:
    runs-on: ubuntu-latest
    needs: preChecks
    steps:
      - name: Install dependencies
        run: common/scripts/install-run-rush.js install --no-link

      - name: Link dependencies
        run: common/scripts/install-run-rush.js link

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Build
        run: common/scripts/install-run-rush.js rebuild --verbose

  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Run tests
        run: common/scripts/install-run-rush.js test

  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        if: ${{ github.ref == 'refs/heads/master' }}
        run: common/scripts/install-run-rush.js publish -p -b master --include-all --set-access-level=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
