import { Test } from 'ts-toolbelt';
import { Sort } from '../src';

const { checks, check } = Test;

type TestModel = {
  name: 'TestModel';
  kind: 'single-model';
  properties: {
    name: {
      kind: 'field';
      type: [string];
      metadata: {
        hideable: true;
        sortable: true;
      };
    };
    createdAt: {
      kind: 'field';
      type: [string];
      metadata: {
        autogenerated: true;
        required: true;
        sortable: false;
        hideable: false;
      };
    };
  };
};
type Result = '+name' | '-name';
type Test = Sort<TestModel>;

checks([check<Sort<TestModel>, Result | Result[], Test.Pass>()]);
