import { Test } from '@kraftr/common';
import { Field } from '../../src';

const { checks, check } = Test;

type TestModel = {
  name: 'Test';
  kind: 'single-model';
  properties: {
    name: {
      kind: 'field';
      type: [string];
      metadata: {
        hideable: true;
      };
    };
    createdAt: {
      kind: 'field';
      type: [string];
      metadata: {
        autogenerated: true;
        required: true;
        hideable: false;
      };
    };
  };
};

type Result = '+name'[] | '-name'[];
type Test = Field<TestModel>;

checks([check<Field<TestModel>, Result, Test.Pass>()]);
